services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dwc-frontend-service
    ports:
      - "5173:80"
    restart: unless-stopped
    # depends_on:
    #   - backend
    environment:
      - NODE_ENV=production
    networks:
      - dwc-network

  # backend:
  #   container_name: dwc-backend-service
  # kafka:
  #   container_name: dwc-kafka-service
  # redis:
  #   container_name: dwc-redis-service

networks:
  dwc-network:
    driver: bridge